name: GitHub-CI for find_log4j

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows MinGW", artifact: "Windows-MinGW.tar.bz2",
            os: windows-latest,
            cc: "gcc", cxx: "g++"
          }
        - {
            name: "Ubuntu GCC", artifact: "Linux.tar.bz2",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
        - {
            name: "macOS Clang", artifact: "macOS.tar.bz2",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }
    steps:
    - uses: actions/checkout@v1
    - name: Prerequisite miniargv
      run: |
        git clone https://github.com/brechtsanders/miniargv
        cd miniargv
        make install PREFIX=../deps DOXYGEN= CC=${{ matrix.config.cc }}
    - name: Prerequisite libdirtrav
      run: |
        git clone https://github.com/brechtsanders/libdirtrav
        cd libdirtrav
        make install PREFIX=../deps DOXYGEN= CC=${{ matrix.config.cc }}
    - name: Prerequisite libmultifinder
      run: |
        git clone https://github.com/brechtsanders/libmultifinder
        cd libmultifinder
        make install PREFIX=../deps DOXYGEN= CC=${{ matrix.config.cc }}
    - name: Compile, install, package
      run: |
        make install PREFIX=build_result STATIC=1 CC=${{ matrix.config.cc }} CFLAGS=-Ideps/include LDFLAGS=-Ldeps/lib
        tar cfj ./${{ matrix.config.artifact }} --strip-components=1 build_result
    - name: Pack
      run: |
        tar cfj ./${{ matrix.config.artifact }} --strip-components=1 build_result
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: ./${{ matrix.config.artifact }}
        name: ${{ matrix.config.artifact }}
